'use strict';
const $=id=>document.getElementById(id), input=$('contract'),scan=$('scan');
const modules={supply:['Total Supply','Circulating Supply','Burn Address Balance','Next Unlock'],whales:['Holder count','Largest Wallet %','Top 10 %','Top 20 %'],control:['Mint','Pause','Blacklist','Owner / Admin','Proxy','AccessControl'],liquidity:['Liquidity USD','24H Volume','DEX / pair count','Primary pair','LP status'],claims:['Claim | Found Data | Result'],mechanics:['Buy Tax %','Sell Tax %','Transfer Tax %','Burn mechanism','Buyback & Burn','Burn allocation %','Tax settings mutable','Owner / Admin / Proxy']};
function compact(v){if(v===null||v===undefined)return 'NOT VERIFIED';const n=Number(v);if(!Number.isFinite(n))return String(v);for(const [d,s]of [[1e9,'B'],[1e6,'M'],[1e3,'K']])if(Math.abs(n)>=d)return (n/d).toFixed(1).replace(/\.0$/,'')+s;return new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(n);}
function field(f){if(!f||f.value===null||f.value===undefined)return 'NOT VERIFIED';if(typeof f.value==='string'&&f.value.startsWith('0x'))return f.value;return String(f.value)+' · '+f.status.replaceAll('_',' ');}
const cards={};
for(const [name,labels]of Object.entries(modules)){const card=document.querySelector('.card.'+name);card.querySelectorAll('.row,.badge,.details').forEach(x=>x.remove());const values=labels.map(label=>{const row=document.createElement('div');row.className='row';const span=document.createElement('span');span.textContent=label;const b=document.createElement('b');b.textContent='—';row.append(span,b);card.append(row);return b;});const badge=document.createElement('div');badge.className='badge';badge.textContent='NOT SCANNED';const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='View evidence';details.append(summary,pre);card.append(badge,details);cards[name]={values,badge,pre};}
function render(name,values,status,data){const x=cards[name];x.values.forEach((b,i)=>{const v=values[i]??'NOT VERIFIED';b.textContent=String(v);});x.badge.textContent=status.replaceAll('_',' ');x.badge.className='badge';x.pre.textContent=JSON.stringify(data,null,2);}
async function request(route,a){const r=await fetch('/api/'+route+'?address='+encodeURIComponent(a),{signal:AbortSignal.timeout(45000),cache:'no-store'});if(!r.ok)throw Error();const d=await r.json();if(!d.ok)throw Error();return d;}
async function startScan(){if(scan.disabled)return;const a=input.value.trim();if(!/^0x[0-9a-f]{40}$/i.test(a)){$('helper').textContent='Enter a valid contract address.';return;}scan.disabled=true;$('token').classList.add('show');$('address').textContent=a;$('tokenName').textContent='Token scan';$('tokenMeta').textContent='';$('scanStatus').textContent='SCANNING';for(const name of Object.keys(cards))render(name,modules[name].map(()=>'…'),'SCANNING',{});
 const supplyState={};let successes=0;
 const supplyRender=()=>{const s=supplyState.supply,m=supplyState.market,u=supplyState.unlock;render('supply',[compact(s?.totalSupply?.amount),m?.status==='SOURCE_REPORTED'?compact(m.circulatingSupply):'NOT VERIFIED',compact(s?.burnAddressBalance?.amount),u?.nextUnlock?.date||'NO SOURCE-REPORTED SCHEDULE'],s?.totalSupply?'PARTIAL_ON_CHAIN':'NOT_VERIFIED',supplyState);};
 const jobs=['token','supply','market','unlock','holders','control','liquidity','claims','mechanics'].map(async route=>{try{const d=await request(route,a);successes++;
 if(route==='token'){const t=d.token;$('tokenName').textContent=(t.name||'Token')+(t.symbol?' ('+t.symbol+')':'');$('tokenMeta').textContent='Arc · Chain 5042 · Decimals: '+t.decimals;}
 else if(['supply','market','unlock'].includes(route)){supplyState[route]=d;supplyRender();}
 else if(route==='holders')render('whales',[compact(d.holderCount),compact(d.largestWalletPct),compact(d.top10Pct),compact(d.top20Pct)],d.status,d);
 else if(route==='control')render('control',[field(d.mint),field(d.pause),field(d.blacklist),field(d.owner)+' / '+field(d.admin),field(d.proxy),field(d.accessControl)],d.status,d);
 else if(route==='liquidity')render('liquidity',[d.liquidityUsd===null?'NOT VERIFIED':'$'+compact(d.liquidityUsd),d.volume24h===null?'NOT VERIFIED':'$'+compact(d.volume24h),d.pairCount===null?'NOT VERIFIED':d.dexCount+' / '+d.pairCount,d.primaryPair,field(d.lpStatus)],d.status,d);
 else if(route==='claims')render('claims',['NO CLAIMS SUPPLIED'],d.status,d);
 else if(route==='mechanics')render('mechanics',[field(d.buyTax),field(d.sellTax),field(d.transferTax),field(d.burnMechanism),field(d.buybackAndBurn),field(d.burnAllocation),field(d.taxSettingsMutable),field(d.owner)+' / '+field(d.admin)+' / '+field(d.proxy)],d.status,d);
 }catch{if(['supply','market','unlock'].includes(route)){supplyState[route]={status:'NOT_VERIFIED',reason:'DATA UNAVAILABLE'};supplyRender();}else if(route!=='token'){const name=route==='holders'?'whales':route;render(name,modules[name].map(()=>'NOT VERIFIED'),'DATA_UNAVAILABLE',{reason:'Source unavailable'});}}
 });
 await Promise.allSettled(jobs);$('scanStatus').textContent=successes?'SCAN COMPLETE · CHECK EVIDENCE':'DATA UNAVAILABLE';$('helper').textContent='Missing evidence is marked NOT VERIFIED. Market depth does not guarantee an exit without slippage.';scan.disabled=false;
}
scan.addEventListener('click',startScan);input.addEventListener('keydown',e=>{if(e.key==='Enter')startScan();});
